name: Generate terraform docs

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - audit-serviceaccount
          - authorize-private-service
          - bucket-events
          - cloudevent-broker
          - cloudevent-trigger
          - cloudevent-recorder
          - regional-go-service
          - regional-service
          - serverless-gclb
          - networking
          - dashboard/service
          - dashboard/job
          - dashboard/cloudevent-receiver
          - prober
          - cron
          - configmap
          - secret
          - github-wif-provider
          - github-gsa
          - github-events

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
        with:
          working-dir: modules/${{ matrix.module }}
          output-file: README.md
          output-method: inject
          fail-on-diff: "true"

      - if: failure()
        run: cat modules/${{ matrix.module }}/README.md

  conclusion:
    permissions:
      actions: read

    needs: docs
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5 # v3.0.3

      - if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0

      - if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 1
