name: Generate terraform docs

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
        - authorize-private-service
        - cloudevent-broker
        - cloudevent-trigger
        - cloudevent-recorder
        - otel-collector
        - networking
        - dashboard/service
        - dashboard/job
        - dashboard/cloudevent-receiver

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          working-dir: ${{ matrix.module }}
          output-file: README.md
          output-method: inject
          fail-on-diff: "true"

      - if: failure()
        run: cat ${{ matrix.module }}/README.md
