name: Generate terraform docs

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - authorize-private-service
          - bucket-events
          - cloudevent-broker
          - cloudevent-trigger
          - cloudevent-recorder
          - regional-go-service
          - regional-service
          - serverless-gclb
          - networking
          - dashboard/service
          - dashboard/job
          - dashboard/cloudevent-receiver
          - prober
          - cron
          - configmap
          - secret
          - github-bots
          - github-wif-provider
          - github-gsa
          - github-events
          - workqueue

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: terraform-docs/gh-actions@cca78c27ac9e2b6545debf2ecae9df930fd3461c # v1.2.2
        with:
          working-dir: modules/${{ matrix.module }}
          output-file: README.md
          output-method: inject
          fail-on-diff: "true"

      - if: failure()
        run: cat modules/${{ matrix.module }}/README.md

  conclusion:
    permissions:
      actions: read

    needs: docs
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5 # v3.0.3

      - if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0

      - if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 1
