name: Validate, Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-validate:
    name: "Terraform fmt and validate"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - run: terraform fmt -check

      - run: |
          terraform init
          terraform validate
