name: Validate, Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-validate:
    name: "Terraform fmt and validate"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0

      - run: terraform fmt -check

      - run: |
          terraform init
          terraform validate
